[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
  "BSD-3-Clause",
  "Unlicense",
  "Unicode-DFS-2016",
]
confidence-threshold = 0.95
copyleft = "deny"
default = "deny"
private = {ignore = true}
unlicensed = "deny"

[advisories]
notice = "deny"
unmaintained = "deny"
unsound = "deny"
vulnerability = "deny"

[bans]
multiple-versions = "allow"
